#Docker image to see if we get /tmp directory in our Docker container, by default or not
FROM ubuntu
WORKDIR /myWorkingDirectory
RUN echo "Hi, from Docker Container">file1
RUN touch file2
RUN export CITY=NewYork
ENV MYNAME Roshan
COPY ram file3
COPY krishna file4
